meta:
  engine: 4.1.0
  name: souffle
  version: 0.1
  ref: &kb_ref "Souffle"
  author: "Felipe Coury"
  url: &kb_url https://github.com/fcoury/souffle # Replace with your repo if you create one
  footprint: &switch_footprint "pg1316s"
  switch:
    $extends: presets.pg1316s

presets:
  pg1316s:
    # Key and keycap measures
    kx: cx # spacing between key centers (X-axis)
    ky: cy # spacing between key centers (Y-axis)
    ks: 19 # horizontal space between columns (default: 19)
    kp: 17.5 # vertical padding between keys (deafult: 19)
    kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
    kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
    keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
    keych: 16.5 # keycap height (cherry: 18, choc: 16.5)
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: 4.7 # Led Y position relative to the switch center
    led_rotation: 0 # Led rotation
    vertical_underglow_shift: -kp + 7.8 # How much to shift underglow leds tied to keys
    vertical_diode_shift: 1.5 # How much to shift to avoid overlap
    horizontal_diode_shift: -0.5 kcow - 0.85
    diode_rotation: 0 # Diode rotation
    switch_rotation: 0

units:
  # The following statements will make the content of the preset
  # available in the units context
  $extends: meta.switch

  hand_rotation: 0

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  # Case variables
  case_wall_thickness: 1.2
  pcb_to_case_wall_tolerance: 0.25
  bottom_plate_thickness: 1.0
  top_plate_thickness: 1.6
  internal_distance_between_plates: 4

points:
  zones:
    matrix:
      key:
        padding: kp
        spread: ks
        tags:
          - key
          - matrix_key
      anchor:
        rotate: hand_rotation
        shift: [100, -100] # Fix KiCad placement
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
        ring:
          key:
            stagger: 0.25 kp
            column_net: C2
        middle:
          key:
            stagger: 0.125 kp
            column_net: C3
        index:
          key:
            stagger: -0.125 kp
            column_net: C4
        inner:
          key:
            stagger: -0.125 kp
            column_net: C5
      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1
        number:
          row_net: R0

    thumbfan:
      key:
        padding: kp
        spread: ks
        stagger: 0
      anchor:
        ref: matrix_middle_bottom
        shift: [-1.0 ks, -1.6 kp] # Further adjusted anchor shift to bring MUCH closer and slightly down
      columns:
        inward: # Closest thumb key to the main matrix
          key:
            column_net: C1
            shift: [-0.2 ks, 0.2 kp] # Shift inward key INWARDS and slightly up, fine-tuned
        mid: # Middle thumb key
          key:
            column_net: C2
            shift: [-0.2 ks, 0.4 kp] # Shift inward key INWARDS and slightly up, fine-tuned
        outward: # Outward thumb key
          key:
            column_net: C3
            shift: [-0.2 ks, 0.4 kp] # Shift inward key INWARDS and slightly up, fine-tuned
        extra_outward: # Extra outward thumb key
          key:
            column_net: C4
            shift: [-0.2 ks, 0 kp] # Shift inward key INWARDS and slightly up, fine-tuned
            splay: -15
        big_outward: # The space/enter key 1.5u
          key:
            column_net: C5
            shift: [-0.1 ks, -0.2kp]
            splay: -15
            tags:
              - key_1_5u
      rows:
        home:
          row_net: R4 # New row net for thumb cluster

outlines:
  _matrix_outline: # Redefined with more points for better contour
    - what: polygon
      points:
        # Top Row (mostly unchanged)
        # cols: outer, pinky, ring, middle, index, inner
        # rows: number, top, home, bottom
        - ref: matrix_outer_number
          shift: [-ks * 0.47 + 0.01, kp * 0.475 - 0.015]
        - ref: matrix_ring_number
          shift: [-ks * 0.47 + 0.01, kp * 0.225 - 0.014]
        - ref: matrix_ring_number
          shift: [-ks * 0.47 + 0.01, kp * 0.475 - 0.015]
        - ref: matrix_middle_number
          shift: [-ks * 0.47 + 0.01, kp * 0.35 - 0.015]
        - ref: matrix_middle_number
          shift: [-ks * 0.47 + 0.01, kp * 0.468 - 0.005]
        - ref: matrix_middle_number
          shift: [ks * 0.478, kp * 0.468 - 0.005]
        - ref: matrix_middle_number
          shift: [ks * 0.478, kp * 0.35 - 0.015]
        - ref: matrix_index_number
          shift: [ks * 0.478, kp * 0.475 - 0.015]
        - ref: matrix_index_number
          shift: [ks * 0.478, kp * 0.34 + 0.052]
        - ref: matrix_inner_number
          shift: [ks * 0.478, kp * 0.468 - 0.005]

        # - ref: mcu_cover_top_right
        #   # shift: [1, -2]
        # - ref: mcu_cover_bottom_right
        #   shift: [0, -30]
        # --- Thumb Cluster Contour --- (New points to follow thumb keys)
        # cols: inward, mid, outward, extra_outward, big_outward
        # rows: home
        - ref: thumbfan_big_outward_home # Start of thumb cluster contour
          shift: [0.55 kp, -0.6 kp]
        - ref: thumbfan_extra_outward_home
          shift: [-0.6 kp, -0.5 kp]
        - ref: thumbfan_outward_home
          shift: [-0.5 kp, -0.6 kp]
        - ref: thumbfan_mid_home
          shift: [-0.4 kp, -0.8 kp]
        - ref: thumbfan_inward_home
          shift: [-0.5 kp, -0.6 kp]

        # --- Bottom Row Contour --- (New points to follow bottom row keys)
        # cols: outer, pinky, ring, middle, index, inner
        # rows: number, top, home, bottom
        - ref: matrix_outer_bottom # Start of bottom row contour
          shift: [-0.5 kp, -0.7 kp]
        # - ref: matrix_outer_bottom
        #   shift: [ks * 0.478 + 0.1 kp, -kp * 0.485 - 0.1 kp] # Adjusted: slightly outwards and down
        # - ref: matrix_middle_bottom
        #   shift: [0, -kp * 0.6 kp] # Adjusted: Directly below middle_bottom, further down
        # - ref: matrix_ring_bottom
        #   shift: [-ks * 0.47 + 0.012 - 0.1 kp, -kp * 0.485 - 0.6 kp] # Adjusted: Slightly inwards and significantly down
        # - ref: matrix_outer_bottom # End of bottom row contour
        #   shift: [-ks * 0.47 + 0.012 - 0.3 kp, -kp * 0.485 - 0.5 kp] # Adjusted: Further inwards and significantly down

        # - ref: plate_outline_bottom_1 # Re-add the remaining points, may need further adjust
        # - ref: plate_outline_bottom_2
        # - ref: plate_outline_bottom_3
        # - ref: plate_outline_bottom_4
  _screws:
    - what: circle
      where: /screw_pcb/
      radius: screw_radius
  _screw_heads:
    - what: circle
      where: /screw_pcb/
      radius: screw_head_radius

pcbs:
  left:
    template: kicad8
    outlines:
      main:
        outline: _matrix_outline
    footprints:
      m2_screws:
        what: ceoloide/mounting_hole_npth
        where: /screw_mcu/
        params:
          hole_size: screw_diameter
          hole_drill: screw_diameter
      m2_spacers:
        what: ceoloide/mounting_hole_npth
        where: /screw_pcb/
        params:
          hole_size: spacer_diameter
          hole_drill: spacer_diameter

      key_switches:
        what: *switch_footprint
        where: /^matrix_.*|^thumbfan_.*/
        params:
          P1: "{{column_net}}"
          P2: "{{colrow}}"
          P3: ""
        adjust:
          rotate: switch_rotation
