on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*.yaml"
      - ".github/actions/*/action.yaml"
      - "ergogen/footprints/*.js"
      - "ergogen/config.yaml"
      - "kibot/*"
      - "freerouting/*"
      - "package.json"

name: Build
jobs:
  board:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Docker Cache
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs with Ergogen (definition in package.json)
        run: npm run build
      - name: Run KiBot to generate images, gerbers for the plates
        uses: ./.github/actions/kibot
        with:
          boards: frontplate backplate controller_overlay
          config: default
      - name: Run KiBot to generate images, gerbers for the unrouted board
        uses: ./.github/actions/kibot
        with:
          # boards: souffle souffle_wireless
          boards: left
          config: default
      - name: Export DSN file for Freerouting
        uses: ./.github/actions/export-dsn
        with:
          # boards: souffle souffle_wireless
          boards: left
      - name: Autoroute PCB
        uses: ./.github/actions/autoroute
        with:
          # boards: souffle souffle_wireless
          boards: left
      - name: Import SES
        uses: ./.github/actions/import-ses
        with:
          # boards: souffle souffle_wireless
          boards: left
      - name: Run KiBot to generate images, gerbers for the autorouted board
        uses: ./.github/actions/kibot
        with:
          # boards: souffle_autorouted souffle_wireless_autorouted
          boards: left_autorouted
          config: boards
      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: not_about_money
          path: |
            cases
            gerbers
            images
            outlines
            pcbs
